vim.pack.add({
    "https://github.com/nvim-lua/plenary.nvim",
    "https://github.com/nvim-tree/nvim-web-devicons",

    "https://github.com/neovim/nvim-lspconfig",
    { src = "https://github.com/saghen/blink.cmp", version = vim.version.range("1") },
    "https://github.com/folke/which-key.nvim",

    "https://github.com/windwp/nvim-ts-autotag",
    { src = "https://github.com/nvim-treesitter/nvim-treesitter", version = "main" },
    "https://github.com/neovim-treesitter/treesitter-parser-registry",
    { src = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects", version = "main" },
    "https://github.com/nvim-treesitter/nvim-treesitter-context",
    "https://github.com/windwp/nvim-autopairs",
    "https://github.com/nvim-lualine/lualine.nvim",
    "https://github.com/akinsho/bufferline.nvim",
    "https://github.com/brenoprata10/nvim-highlight-colors",
    "https://github.com/uga-rosa/ccc.nvim",
    "https://github.com/folke/noice.nvim",
    "https://github.com/MunifTanjim/nui.nvim",
    "https://github.com/grapp-dev/nui-components.nvim",
    "https://github.com/rcarriga/nvim-notify",
    "https://github.com/stevearc/conform.nvim",
    "https://github.com/rafamadriz/friendly-snippets",
    "https://github.com/junegunn/fzf.vim",
    "https://github.com/ibhagwan/fzf-lua",
    "https://github.com/pmizio/typescript-tools.nvim",
    "https://github.com/stevearc/aerial.nvim",
})
